### ISSUE TITLE
结果复现问题

### ISSUE THREAD

**Issue by Delete12137** [hw-tony/LA-Net-Landmark-Aware-Learning-for-Reliable-Facial-Expression-Recognition-under-Label-Noise#1]
你好，非常感谢你们的工作。最近我在复现你们的工作时，发现结果相较于你们论文中公布的结果差距有些大。我尝试了调整学习率从0.0001-0.009，其中最佳的结果是论文中提到的0.001学习率，但他的结果与论文中公布的性能相差五六个点（在每一噪音率下）。

ps.以上实验我是在四台RTX 2080ti上进行的，且除了学习率参数，其他参数并未做修改

**Comment by hw-tony** [comment]
如此巨大的性能差异可能是您在训练过程中没有正确加载预训练模型导致的。一般来说，FER任务的backbone是否使用良好的预训练参数会有明显的差异。
另一方面，我们的实验采用了自己在MS-Celeb数据集上预训练的backbone，其在预训练阶段采用了与dataloader.py文件中所用的一样的数据扩增方法，预处理的mean和std也是按照MS-Celeb中的图像进行计算的。该数据扩增方法对原始图像的扰动相对较强。您可能需要根据您的预训练模型的训练策略来相应调整数据扩增的策略，否则初始化的参数可能无法接受dataloader.py中这一相对较强的augmentation。
另外，我也会检查一下开源代码在整理过程中是否出错。但这需要在一段时间后进行，因为最近需要赶别的论文ddl。

**Comment by Delete12137** [comment]
好的，非常感谢您的回复在 2023年9月9日，23:17，hw-tony ***@***.***> 写道：﻿
如此巨大的性能差异可能是您在训练过程中没有正确加载预训练模型导致的。一般来说，FER任务的backbone是否使用良好的预训练参数会有明显的差异。
另一方面，我们的实验采用了自己在MS-Celeb数据集上预训练的backbone，其在预训练阶段采用了与dataloader.py文件中所用的一样的数据扩增方法，预处理的mean和std也是按照MS-Celeb中的图像进行计算的。该数据扩增方法对原始图像的扰动相对较强。您可能需要根据您的预训练模型的训练策略来相应调整数据扩增的策略，否则初始化的参数可能无法接受dataloader.py中这一相对较强的augmentation。
另外，我也会检查一下开源代码在整理过程中是否出错。但这需要在一段时间后进行，因为最近需要赶别的论文ddl。
