### ISSUE TITLE
论文疑问

### ISSUE THREAD

**Issue by Delete12137** [hw-tony/LA-Net-Landmark-Aware-Learning-for-Reliable-Facial-Expression-Recognition-under-Label-Noise#3]
你好，非常感谢你们的工作。
请问论文中的landmark网络也是一个面部表情分类网络，还是如名字一样是用来提取面部眼睛鼻子等特征点的？后者感觉一些损失函数就说不通了

**Comment by hw-tony** [comment]
landmark网络的优化目标是人脸关键点，实际用的是awing loss，优化目标是按照面部关键点计算的heat map，从学习关键点的角度会比直接与点坐标计算L2距离好一点。
landmark网络会跟expression网路共享一些底层。

**Comment by Delete12137** [comment]
好的谢谢
